rango/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
     path('category/<slug:category_name_slug>/', 
        views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('statistics/', views.statistics, name='statistics'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('the_fast_and_the_furious/', views.the_fast_and_the_furious, name='the_fast_and_the_furious'),
    path('the_expendables/', views.the_expendables, name='the_expendables'),
    path('deadpool/', views.deadpool, name='deadpool'),
    path('hangover/', views.hangover, name='hangover'),
    path('home_alone/', views.home_alone, name='home_alone'),
    path('minions/', views.minions, name='minions'),
    path('coco/', views.coco, name='coco'),
    path('titanic/', views.titanic, name='titanic'),
    path('black_panther/', views.black_panther, name='black_panther'),
    path('transformers/', views.transformers, name='transformers'),
    path('back_to_the_future/', views.back_to_the_future, name='back_to_the_future'),
    path('profile/',views.user_profile, name = "profile"),
    path('deleteuser/',views.delete_user, name = "deleteuser"),
    path('contact_us_list/',views.all_contactus, name = "list_contactus"),
    path('add_review/', views.add_review, name='add_review'),
    path('all_reviews/',views.all_reviews, name = "all_reviews"),
]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    MAX_PHONE_LENGTH = 15
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #website = models.URLField(blank=True)
    #picture = models.ImageField(upload_to='profile_images', blank=True)
    phone = models.CharField(max_length = MAX_PHONE_LENGTH)

    def __str__(self):
        return self.user.username

class ContactUs(models.Model):
    NAME_MAX_LENGTH = 128
    SUBJECT_MAX_LENGTH = 5000
    name =  models.CharField(max_length=NAME_MAX_LENGTH)
    subject = models.CharField(max_length=SUBJECT_MAX_LENGTH)
    class Meta:
        verbose_name_plural = 'Contact us queries'
    def __str__(self):
        return self.name


class Review(models.Model):
    NAME_MAX_LENGTH = 128
    FILM_MAX_LENGTH = 128
    SUBJECT_MAX_LENGTH = 5000
    title =  models.CharField(max_length=NAME_MAX_LENGTH)
    film =  models.CharField(max_length=FILM_MAX_LENGTH)
    review = models.CharField(max_length=SUBJECT_MAX_LENGTH)

    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from rango.models import ContactUs, Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                            help_text="Please enter category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                        help_text="Please enter the title of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page

        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field.widget.attrs.get('class'):
                field.widget.attrs['class'] += ' form-control'
            else:
                field.widget.attrs['class']='form-control'    

                

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone',)
            
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field.widget.attrs.get('class'):
                field.widget.attrs['class'] += ' form-control'
            else:
                field.widget.attrs['class']='form-control'  
        


class ContactUsForm(forms.ModelForm):
    name = forms.CharField(max_length=ContactUs.NAME_MAX_LENGTH, help_text="Name",)
    subject = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write Something'}), max_length=ContactUs.SUBJECT_MAX_LENGTH, help_text="Subject",  )

    class Meta:
        model = ContactUs
        fields = ('name','subject')

class ReviewForm(forms.ModelForm):
    title = forms.CharField(max_length=ContactUs.NAME_MAX_LENGTH, help_text="Title",)
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write Something'}), max_length=ContactUs.SUBJECT_MAX_LENGTH, help_text="Review",  )
    film = forms.CharField(max_length=ContactUs.NAME_MAX_LENGTH, help_text= 'Film')

    class Meta:
        model = ContactUs
        fields = ('title','review','film')

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.models import Category, ContactUs, Page, Review, User,UserProfile
from rango.forms import CategoryForm, ContactUsForm, PageForm, UserForm, UserProfileForm, ReviewForm
from datetime import datetime
from django.db.models import Count


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    context_dict['extra'] = 'From the model solution on GitHub'
    
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/about.html', context=context_dict)

def the_fast_and_the_furious(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/the_fast_and_the_furious.html', context=context_dict)

def the_expendables(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/the_expendables.html', context=context_dict)

def deadpool(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/deadpool.html', context=context_dict)

def hangover(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/hangover.html', context=context_dict)

def home_alone(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/home_alone.html', context=context_dict)

def minions(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/minions.html', context=context_dict)

def coco(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/coco.html', context=context_dict)

def titanic(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/titanic.html', context=context_dict)

def black_panther(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/black_panther.html', context=context_dict)

def transformers(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/transformers.html', context=context_dict)

def back_to_the_future(request):
    
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/back_to_the_future.html', context=context_dict)

def statistics(request):

    user_count = User.objects.count()
    film_count = Page.objects.count()
    list1=[]
    list2=[]
    categories = Page.objects.filter().order_by('category').values('category__name').annotate(count=Count('category__name'))
    for i in categories:
        list1.append(str(i.get('category__name')))
        list2.append(i.get('count'))
   

    context_dict = {'user_count' : user_count,
                    'film_count' : film_count,
                    'list1' :list1 ,
                    'list2' : list2,
                    }
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/statistics.html', context=context_dict)

def contact_us(request):
    form = ContactUsForm()

    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
    
    return render(request, 'rango/contact_us.html', {'form': form})


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
    
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None
    
    # You cannot add a page to a Category that does not exist... DM
    if category is None:
        return redirect(reverse('rango:index'))

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)  # This could be better done; for the purposes of TwD, this is fine. DM.
    
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'rango/register.html', context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits

@login_required
def user_profile(request):
    registered = False
    current_user =  request.user
    current_user_id = request.user.id
    current_user_username = current_user.username
    user = User.objects.get(username = current_user_username)
    try:
        userprofile = UserProfile.objects.get(user = user)
    except:
        UserProfile.objects.create(user=user, phone = '')
        userprofile = UserProfile.objects.get(user = user)
    user_form = UserForm(request.POST or None, instance = user)

    profile_form = UserProfileForm(request.POST or None, instance=userprofile)


    if user_form.is_valid() and profile_form.is_valid():
        current_user =  request.user
        #current_user.delete()
        
        user = user_form.save()
        user.set_password(user.password)
        user.save()

        profile = profile_form.save(commit=False)
        profile.user = user

        if 'picture' in request.FILES:

templates/rango/Reviews_list.html
{% extends 'rango/base.html' %}
{% load static  %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}


{% if user.is_staff %}

<h1>List of Reviews</h1>

{% for i in  review_list%}
<div class="card  m-5">
    <!-- <div class="card-header">
     Title: {{i.title}}}, Review for movie: {{i.film}}, 
    </div>
    <div class="card-body">
      
      <p class="card-text">{{i.review}}</p> -->
      
    </div>
  </div>  
{% endfor %}

{% else %}
<script>
    window.location.href = "{% url 'rango:index' %}";
    </script>
    
{% endif %}

{% endblock %}

templates/rango/add_review.html
{% extends 'rango/base.html' %}
{% load static  %}

{% block title_block %}
    Contact us
{% endblock %}

{% block body_block %}

<h1 class="heading">Add a review</h1><br />
<div class="contact-info">Fill in the form bellow if you would like to leave a review:<br />
   
</div>

<div class = "paddingbtm60">
   <!-- the contact form is added to the page -->
 
    <form id="ReviewForm" method="post" action="{% url 'rango:add_review'%}">
        {% csrf_token %}
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Add review"/>
    </form>

</div>

{% endblock %}

templates/rango/back_to_the_future.html
{% extends 'rango/base.html' %}
{% load static  %}

{% block title_block %}
    Contact us
{% endblock %}

{% block body_block %}
<br />
<h1 class="title">Back to the Future</h1> 
<h6 class="info"><i>1985, Science Fiction, 1h 56m</i></h6>
<! –– the photo of the film is inserted on the right side of the page ––>
<div class="photo"><img src="{% static 'images/back.jpg' %}"
    alt="Photo of Back to the Future"/></div>

<div>
    <h5 class="description"> Description of the film:</h5><br />
    <p class="desc-text">In this 1980s sci-fi classic, small-town California teen Marty McFly (Michael J. Fox) is thrown back into the '50s when an experiment by his eccentric scientist friend Doc Brown (Christopher Lloyd) goes awry. Traveling through time in a modified DeLorean car, Marty encounters young versions of his parents (Crispin Glover, Lea Thompson), and must make sure that they fall in love or he'll cease to exist. Even more dauntingly, Marty has to return to his own time and save the life of Doc Brown.</p>
      <ul class="list"> 
          <li>Director:	Robert Zemeckis </li>
        <li>Producer:	Bob Gale, Neil Canton</li>
       <li> Writer:	Robert Zemeckis, Bob Gale</li>
        </ul> 
</div>
 
    <! –– the embeded trailer of the film is inserted on the right side of the page ––> 
      <div>
        <iframe class="trailer" src="https://www.youtube.com/embed/qvsgGtivCgs" frameborder="0" allowfullscreen></iframe>
      </iframe>
        </div>

        <!-- creating a write a review form -->
        <div class = "paddingbtm60">
        <h3 class="review-title">Write a review</h3>
         <a class="nav-link" href="{% url 'rango:add_review' %}">add a review</a>
    </div>
   
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load static  %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango -
            {% block title_block %}
            Moʃvies
            {% endblock %}
            </title>
            <link rel="stylesheet" href="/static/css/mycss.css"/><!-- adding a css file which will be used in the other templates that extends these ones  -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> <!-- the css for the page headings and design -->
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
            
    </head>
    <body>
 <!-- a upper menu bar to display information for logged in and non logged in users is created bellow -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'rango:index' %}">Homepage</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Category
                        </a>
                        <!-- a dropdown menu to display all the categories is created bellow -->
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item" href="/rango/category/action/">Action</a>
                          <a class="dropdown-item" href="/rango/category/comedy/">Comedy</a>
                          <a class="dropdown-item" href="/rango/category/science-fiction/">Science Fiction</a>
                          <a class="dropdown-item" href="/rango/category/animation/">Animation</a>
                          <a class="dropdown-item" href="/rango/category/drama/">Drama</a>
                        </div>
                      </li>
                </ul>
            </div>
            <div class="navbar-nav mx-auto order-0">
                <li class="nav-item active">
                    <span class="navbar-text">
                        Moʃvies
                      </span>
                </li> 
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'rango:profile' %}">Profile</a></li>
                    <li><a class="nav-link" href="{% url 'rango:logout' %}">Logout</a></li>
                    
                {% else %}
                    <li><a class="nav-link" href="{% url 'rango:register' %}">SIGN UP</a></li>

                    <li><a class="nav-link" href="{% url 'rango:login' %}">LOGIN</a></li>
                {% endif %}
                </ul>
            </div>
        </nav>
       


       
        {% block body_block %}
        {% endblock %}
    




 <!-- a lower menu bar to display fixed information is created bellow -->
    <div class="fixed-bottom">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mx-auto">
              <li > <a class="nav-link" href="{% url 'rango:about' %}">ABOUT US</a></li>
              <li > <a class="nav-link" href="{% url 'rango:contact_us' %}">CONTACT US</a></li>
              <li > <a class="nav-link" href="{% url 'rango:statistics' %}">STATISTICS</a></li>
              {% if user.is_staff %}
                    <li><a class="nav-link" href="{% url 'rango:list_contactus' %}">LIST OF CONTACT US</a></li>
                    {% endif %}
            </ul>
    </nav>
</div>

    </body>
</html>

templates/rango/black_panther.html
{% extends 'rango/base.html' %}
{% load static  %}

{% block title_block %}
    Contact us
{% endblock %}

{% block body_block %}
<br />
<h1 class="title">Black Panther</h1> 
<h6 class="info"><i>2018, Drama, 2h 14m</i></h6>
<! –– the photo of the film is inserted on the right side of the page ––>
<div class="photo"><img src="{% static 'images/black.jpg' %}"
    alt="Photo of Black Panther"/></div>

<div>
    <h5 class="description"> Description of the film:</h5><br />
    <p class="desc-text">After the death of his father, T'Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy suddenly reappears, T'Challa's mettle as king -- and as Black Panther -- gets tested when he's drawn into a conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people.</p>
    <ul class="list"> 
        <li>Director:	Rob Cohen</li>
      <li> Producer:	Neal H. Moritz</li>
     <li> Writer: Gary Scott Thompson, Erik Bergquist, David Ayer, Gary Scott Thompson </li>
      </ul> 
</div>
<! –– the embeded trailer of the film is inserted on the right side of the page ––> 
      <div>
        <iframe class="trailer" src="https://www.youtube.com/embed/xjDjIWPwcPU" frameborder="0" allowfullscreen></iframe>
      </iframe>
        </div>

      <!-- creating a write a review form -->
      <div class = "paddingbtm60">
        <h3 class="review-title">Write a review</h3>
        <a class="nav-link" href="{% url 'rango:add_review' %}">add a review</a>
    </div>
   
{% endblock %}

templates/rango/deadpool.html
{% extends 'rango/base.html' %}
{% load static  %}

{% block title_block %}
    Contact us
{% endblock %}

{% block body_block %}
<br />
<h1 class="title">Deadpool</h1> 
<h6 class="info">2016, Comedy, 1h 48m</i></h6>
<! –– the photo of the film is inserted on the right side of the page ––>
<div class="photo2"><img src="{% static 'images/deadpool.jpg' %}"
    alt="Photo of Deadpool"/></div>

<div>
    <h5 class="description"> Description of the film:</h5><br />
    <p class="desc-text">Wade Wilson (Ryan Reynolds) is a former Special Forces operative who now works as a mercenary. His world comes crashing down when evil scientist Ajax (Ed Skrein) tortures, disfigures and transforms him into Deadpool. The rogue experiment leaves Deadpool with accelerated healing powers and a twisted sense of humor. With help from mutant allies Colossus and Negasonic Teenage Warhead (Brianna Hildebrand), Deadpool uses his new skills to hunt down the man who nearly destroyed his life.</p>
    <ul class="list"> 
        <li> Director:	Tim Miller</li>
      <li> Producer:	Simon Kinberg, Ryan Reynolds, Lauren Shuler Donner</li>
     <li> Writer:	Rhett Reese, Paul Wernick </li>
      </ul>
</div>
    
<! –– the embeded trailer of the film is inserted on the right side of the page ––> 
      <div>
        <iframe class="trailer" src="https://www.youtube.com/embed/ONHBaC-pfsk" frameborder="0" allowfullscreen></iframe>
      </iframe>
        </div>

      <!-- creating a write a review form -->
      <div class = "paddingbtm60">
        <h3 class="review-title">Write a review</h3>
        <a class="nav-link" href="{% url 'rango:add_review' %}">add a review</a>
    </div>
   
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load static  %}

{% block title_block %}
     Restricted Page
{% endblock %}

{% block body_block %}
<h1>Restricted Page</h1>
Since you are logged in, you can see this text!<br />
{{ user.username }} is here!
{% endblock %}
     